/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_darts_DoubleArrayNative */

#ifndef _Included_jp_darts_DoubleArrayNative
#define _Included_jp_darts_DoubleArrayNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    createInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_darts_DoubleArrayNative_createInstance
  (JNIEnv *, jobject);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    destroyInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_darts_DoubleArrayNative_destroyInstance
  (JNIEnv *, jobject);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    setArray
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_jp_darts_DoubleArrayNative_setArray
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    getArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jp_darts_DoubleArrayNative_getArray
  (JNIEnv *, jobject);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_darts_DoubleArrayNative_size
  (JNIEnv *, jobject);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    build
 * Signature: (I[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_jp_darts_DoubleArrayNative_build
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_jp_darts_DoubleArrayNative_open
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    save
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_jp_darts_DoubleArrayNative_save
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    exactMatchSearch
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_jp_darts_DoubleArrayNative_exactMatchSearch
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     jp_darts_DoubleArrayNative
 * Method:    commonPrefixSearch
 * Signature: (Ljava/lang/String;III)[I
 */
JNIEXPORT jobjectArray JNICALL Java_jp_darts_DoubleArrayNative_commonPrefixSearch
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
